# Generated by Django 5.1.5 on 2025-01-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("img_path", models.CharField(default="", max_length=400)),
            ],
        ),
    ]
