# Generated by Django 5.1.5 on 2025-01-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cwapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPPNState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("img_path_ids", models.TextField()),
            ],
        ),
    ]
