# Generated by Django 5.1.5 on 2025-01-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cwapp", "0002_cppnstate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cppnstate",
            name="img_path_ids",
        ),
    ]
