# Generated by Django 5.1.5 on 2025-01-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cwapp", "0003_remove_cppnstate_img_path_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="PureCPPNState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
